server:
  port: 8080
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/policy?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password:
mybatis:
   mapperLocations: classpath:/mapper/*.xml
